server:
  port: 8888

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    host: localhost
    port: 6379
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



