server:
  port: 8888

spring:
  application:
    name: zuul-server
zuul:
  routes:
    # <serviceId>: <path>
    producer: /producer/**
#    producer:
#      path: /producer/**
#      serviceId: producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherSevlet: debug
    org.springframework.cloud.sleuth: debug
