server:
  port: 9080


spring:
  application:
    name: consumer
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health,hystrix.stream
feign:
  sentinel:
    enabled: true


