server:
  port: 9080


spring:
  application:
    name: consumer
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health,hystrix.stream
feign:
  sentinel:
    enabled: true


