server:
  port: 7002

spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    addresses: 127.0.0.1
  cloud:
    stream:
      bindings:
        input:
          destination: zuoban-stream
          group: group-2
          consumer:
            partitioned: true
      binders:
        defaultRabbit:
          type: rabbit
      instance-count: 2
      instance-index: 0

---
spring:
  profiles: 7003
  cloud:
    stream:
      instance-index: 1
server:
  port: 7003
