server:
  port: 7002

spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    addresses: 127.0.0.1
  cloud:
    stream:
      bindings:
        input:
          destination: zuoban-stream
          group: group-1
        inputOrder:
          destination: mqTestOrder
        outputOrder:
          destination: mqTestOrder
      binders:
        defaultRabbit:
          type: rabbit

---
spring:
  profiles: 7003
server:
  port: 7003
