server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.leftsite.cn/zuoban/springcloud2020-config.git
  application:
    name: config-server

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
