server:
  port: 8090
spring:
  application:
    name: producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherSevlet: debug
    org.springframework.cloud.sleuth: debug

---
spring:
  profiles: 8081
server:
  port: 8081
