server:
  port: 8090
spring:
  application:
    name: producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherSevlet: debug
    org.springframework.cloud.sleuth: debug

---
spring:
  profiles: 8081
server:
  port: 8081
